# Generated by Django 3.2.19 on 2023-12-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('laminat', 'ламинат'), ('ekospon', 'экошпон'), ('pvh', 'ПВХ')], max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('steel', 'метал'), ('wood', 'дерево'), ('furniture', 'фурнитура')], max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='название')),
                ('body', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание товара')),
                ('praice', models.CharField(max_length=10, verbose_name='Цена')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('maker', models.CharField(max_length=100, verbose_name='Изготовитель')),
                ('matter', models.CharField(max_length=100, verbose_name='Материал изготовления')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=100)),
                ('code', models.CharField(max_length=20, verbose_name='Артикул')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='doors.category', verbose_name='Категория товара')),
                ('category_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_1', to='doors.category_1', verbose_name='Подкатегория')),
                ('save_product', models.ManyToManyField(related_name='save_producte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
